name: 官方实时流量徽章同步

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨自动跑一次
  workflow_dispatch: # 允许你手动点击测试

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: 同步官方Clone数据到专属隔离分支
        uses: albertoarena/github-traffic-badge@v1.0.1
        env:
          INPUT_REPO: ${{ github.repository }}
          INPUT_TOKEN: ${{ secrets.TRAFFIC_TOKEN }}
          INPUT_TRAFFIC_BRANCH: traffic 
